### ISSUE TITLE
Build failure from RELRO in .vector section

### ISSUE THREAD

**Issue by orlitzky** [sophgo/zsbl#66]
Hi, if I am using the distro toolchain on the pioneer (and not cross-compiling with the bundled GCC), I get a build failure due to a relocation:

```
ld -r -o libzsbl.a --whole-archive common/built-in.a arch/riscv/src/built-in.a drivers/built-in.a lib/built-in.a plat/built-in.a test/built-in.a --no-whole-archive
/usr/lib/gcc/riscv64-unknown-linux-musl/14/../../../../riscv64-unknown-linux-musl/bin/ld: arch/riscv/src/vector.o: warning: relocation against `_fw_start' in read-only section `.vector'
/usr/lib/gcc/riscv64-unknown-linux-musl/14/../../../../riscv64-unknown-linux-musl/bin/ld: read-only segment has dynamic relocations
collect2: error: ld returned 1 exit status
```

This can be worked around with `-Wl,-znotext` but there is probably a better solution.

**Comment by SophgoChaoWei** [comment]
The commit defa6ad3bd13c8543786b5f408fbdc5b7a636d2f solved this issue.
This static library is not needed any more, I just remove it.
It is a story why a static library generates. This project initially forked from another project. In that project, BSP software team should provide a c runtime for TPU teams. So the linking work is done when building TPU coprocessor firmware. But that feature is not needed in this project.
Thanks.
