### ISSUE TITLE
Build failure with -fstack-protector

### ISSUE THREAD

**Issue by orlitzky** [sophgo/zsbl#67]
Hi, when using the distro toolchain on my pioneer, I get build failures that are due to the stack protector symbols being unresolved (the compiler enables `-fstack-protector` by default). For example,

```
ld -r -o libzsbl.a --whole-archive common/built-in.a arch/riscv/src/built-in.a drivers/built-in.a lib/built-in.a plat/built-in.a test/built-in.a --no-whole-archive
/usr/lib/gcc/riscv64-unknown-linux-musl/14/../../../../riscv64-unknown-linux-musl/bin/ld: drivers/sd/mmc.o: in function `mmc_send_cmd':
/home/mjo/src/zsbl.git/build/../drivers/sd/mmc.c:40:(.text.mmc_send_cmd+0x8): undefined reference to `__stack_chk_guard'
/usr/lib/gcc/riscv64-unknown-linux-musl/14/../../../../riscv64-unknown-linux-musl/bin/ld: /home/mjo/src/zsbl.git/build/../drivers/sd/mmc.c:62:(.text.mmc_send_cmd+0x90): undefined reference to `__stack_chk_fail'
...
```

One way to work around this is with `-fno-stack-protector`, but maybe there is a way to keep the stack protection? If this were a normal userland program, it would need to link with libc and/or libssp_nonshared depending on the libc. But obviously that won't work for ZSBL. I do know that the linux kernel has some support for a stack protector though so there must be some way to do it.

**Comment by SophgoChaoWei** [comment]
The commit ec9b9f5fa57f17cb351085eae0bb0698925ef597 solved this issue.
Thanks your feedback.
